version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    ports:
    - "5432:5432"
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloudnative

  desafio:
    build:
      context: .
    container_name: desafio
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    tty: true
    restart: always