apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
    DATABASE_HOST:     {{ .Values.database.host     | quote }}
    DATABASE_USER:     {{ .Values.database.username | quote }}
    DATABASE_PASSWORD: {{ .Values.database.password | quote }}
    DATABASE_DATABASE: {{ .Values.database.database | quote }}
