apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  POSTGRES_DB:       {{ .Values.postgres.auth.database }}
  POSTGRES_USER:     {{ .Values.postgres.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password }}