apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
    DB_PORT: {{ .Values.postgres.spec.containerPort | quote }}
    DB_USER: {{ .Values.postgres.auth.username | quote }}
    DB_PASS: {{ .Values.postgres.auth.password | quote }}
    DB_NAME: {{ .Values.postgres.auth.database | quote }}