apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.spec.containerPort }}
      targetPort: {{ .Values.postgres.spec.containerPort }}
  selector:
   app: {{ .Chart.Name }}