replicaCount: 1

image:
  repository: lukeinstruct/desafio
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 20
  targetMemoryUtilizationPercentage: 20

nodeSelector: {}

tolerations: []

affinity: {}

database:
  username: postgres
  password: postgres
  database: cloudnative
  host: database
